id: A718E876C
title: fA81C
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:05:52.824633
  last_modified_at: 2022-05-27 15:05:52.824642
