id: A718E876C
title: fE0AB
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:05:52.836689
  last_modified_at: 2022-05-27 15:05:52.836695
