id: A718E876C
title: f1972
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:05:52.822579
  last_modified_at: 2022-05-27 15:05:52.822587
